name: Run All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Phase 1: Static Analysis (can run in parallel)
  python-lint:
    name: Python Linting
    uses: ./.github/workflows/python-lint.yml
    
  frontend-lint:
    name: Frontend Linting  
    uses: ./.github/workflows/frontend-lint.yml
    
  security-analysis:
    name: Security Analysis
    uses: ./.github/workflows/security-analysis.yml
  
  # Phase 2: Build Tests (run after linting passes)
  docker-builds:
    name: Docker Container Builds
    needs: [python-lint, frontend-lint]
    uses: ./.github/workflows/docker-builds.yml
  
  # Phase 3: Summary (runs after all tests complete)
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [python-lint, frontend-lint, security-analysis, docker-builds]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Python Linting
        if [ "${{ needs.python-lint.result }}" == "success" ]; then
          echo " Python Linting: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "L Python Linting: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Frontend Linting
        if [ "${{ needs.frontend-lint.result }}" == "success" ]; then
          echo " Frontend Linting: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "L Frontend Linting: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Security Analysis
        if [ "${{ needs.security-analysis.result }}" == "success" ]; then
          echo " Security Analysis: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "L Security Analysis: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Docker Builds
        if [ "${{ needs.docker-builds.result }}" == "success" ]; then
          echo " Docker Builds: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "L Docker Builds: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Overall status
        if [ "${{ needs.python-lint.result }}" == "success" ] && \
           [ "${{ needs.frontend-lint.result }}" == "success" ] && \
           [ "${{ needs.security-analysis.result }}" == "success" ] && \
           [ "${{ needs.docker-builds.result }}" == "success" ]; then
          echo "<‰ **All tests passed successfully!**" >> $GITHUB_STEP_SUMMARY
          exit 0
        else
          echo "=¥ **Some tests failed. Please check the individual job results.**" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi